name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.118.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # https://github.com/settings/tokens/new
          # https://github.com/malkhazpaliani/mestiahotellevel/settings/secrets/actions/new
          personal_token: ${{ secrets.TOKEN }}
          external_repository: malkhazpaliani/malkhazpaliani.github.io
          user_name: malkhazpaliani
          user_email: malkhazpaliani@gmail.com
          publish_branch: main
